# 3 Import your analysis libraries, as well as your new customer data set as a dataframe.

In [4]:
# Import analysis libraries
import pandas as pd
import numpy as np
import os
import scipy

In [5]:
# Define the path
path = 'C:\\Users\\User\\Documents\\Career Foundry\\Data Analytics Immersion\\Data Immersion 4. Python Fundamentals for Data Analysts\\Instacart Basket Analysis'

In [6]:
# Import the new customer data set as dataframe
df = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'customers.csv'), index_col=False)

In [7]:
# Check the dimension for the report
df.shape

(206209, 10)

# 4 Wrangle the data so that it follows consistent logic; for example, rename columns with illogical names and drop columns that don’t add anything to your analysis.

In [9]:
# Check the columns
df.columns

Index(['user_id', 'First Name', 'Surnam', 'Gender', 'STATE', 'Age',
       'date_joined', 'n_dependants', 'fam_status', 'income'],
      dtype='object')

In [10]:
# Rename columns
df = df.rename(columns={
    'First Name': 'first_name',
    'Surnam': 'surname',
    'Gender': 'gender',
    'STATE': 'state',
    'Age': 'age',
    'n_dependants': 'num_dependants',
    'fam_status': 'family_status'})

In [11]:
# Check the columns again
df.columns

Index(['user_id', 'first_name', 'surname', 'gender', 'state', 'age',
       'date_joined', 'num_dependants', 'family_status', 'income'],
      dtype='object')

# 5 Complete the fundamental data quality and consistency checks you’ve learned throughout this Achievement; for example, check for and address missing values and duplicates, and convert any mixed-type data.

In [13]:
df.describe()

             user_id            age  num_dependants         income
count  206209.000000  206209.000000   206209.000000  206209.000000
mean   103105.000000      49.501646        1.499823   94632.852548
std     59527.555167      18.480962        1.118433   42473.786988
min         1.000000      18.000000        0.000000   25903.000000
25%     51553.000000      33.000000        0.000000   59874.000000
50%    103105.000000      49.000000        1.000000   93547.000000
75%    154657.000000      66.000000        3.000000  124244.000000
max    206209.000000      81.000000        3.000000  593901.000000

In [14]:
# Check for mixed-type data
for col in df.columns.tolist():
    weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis=1)
    if len(df[weird]) > 0:
        print(col)

C:\Users\User\AppData\Local\Temp\ipykernel_1476\932240416.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis=1)
C:\Users\User\AppData\Local\Temp\ipykernel_1476\932240416.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis=1)
C:\Users\User\AppData\Local\Temp\ipykernel_1476\932240416.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis=1)
C:\Users\User\AppData\Local\Temp\ipykernel_1476\932240416.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis=1)

first_name

C:\Users\User\AppData\Local\Temp\ipykernel_1476\932240416.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis=1)
C:\Users\User\AppData\Local\Temp\ipykernel_1476\932240416.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis=1)
C:\Users\User\AppData\Local\Temp\ipykernel_1476\932240416.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis=1)
C:\Users\User\AppData\Local\Temp\ipykernel_1476\932240416.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis=1)
C:\Users\User\AppData\Local\Temp\ipykernel_1476\932240416.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis=1)
C:\Users\User\AppData\Local\Temp\ipykernel_1476\932240416.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis=1)

In [15]:
# Convert first_name to string
df['first_name'] = df['first_name'].astype(str)

In [16]:
# Find missing values
df.isnull().sum()

user_id           0
first_name        0
surname           0
gender            0
state             0
age               0
date_joined       0
num_dependants    0
family_status     0
income            0
dtype: int64

In [17]:
# Find duplicates
df_dups = df[df.duplicated()]

In [18]:
# Check duplicates
df_dups

Empty DataFrame
Columns: [user_id, first_name, surname, gender, state, age, date_joined, num_dependants, family_status, income]
Index: []

# No missing values or duplicate entries were found

In [20]:
# Check the dimension
df.shape

(206209, 10)

# 6 Combine your customer data with the rest of your prepared Instacart data. (Hint: Make sure the key columns are the same data type!)

In [22]:
# Import the most uptodate dataframe
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge_updated_with_flags.pkl'))

In [23]:
# Check the columns
ords_prods_merge.columns

Index(['order_id', 'user_id', 'order_number', 'orders_day_of_week',
       'order_hour_of_day', 'days_since_prior_order', 'product_id',
       'add_to_cart_order', 'reordered', 'product_name', 'aisle_id',
       'department_id', 'prices', 'price_range_loc', 'busiest_day',
       'busiest_days_category', 'busiest_period_of_day', 'max_order',
       'loyalty_flag', 'avg_price_per_user', 'spending_flag',
       'median_days_since_order', 'order_frequency_flag'],
      dtype='object')

In [24]:
# Combine the customer data with the updated ords_prods_merge
orders_products_all = pd.merge(df, ords_prods_merge, on='user_id', indicator=True)

In [25]:
# Export data to pkl
orders_products_all.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_all.pkl'))

In [26]:
# Check the dimension
orders_products_all.shape

(32404859, 33)